# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:24-jdk
      options: --user root
      env:
        JAVA_HOME: /opt/java/openjdk
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Xvfb
      run: |
        apt-get update
        apt-get install -y xvfb
        Xvfb :99 -screen 0 1024x768x16 &
        export DISPLAY=:99
        
    - name: Install Maven
      run: |
        apt-get install -y maven
        mvn --version

    - name: Build with Maven
      run: |
        mvn -B package --file pom.xml \
          -Dmaven.compiler.source=24 \
          -Dmaven.compiler.target=24
